baseURL = "http://treatment-effects.com/"
languageCode = "en-us"
title = "A Course on Treatment Effects"
theme = "accessible-minimalism"
disableHugoGeneratorInject = true
enableRobotsTXT = true

# Comment these out since I don't really need a menu at the moment
#[menu]
#  [[menu.main]]
#    name = "Home"
#    url = "/"
#    weight = 1
# Comment these out since there won't be any blog posts
#  [[menu.main]]
#    name = "Posts"
#    url = "/posts/"
#    weight = 2
