baseURL = "http://treatment-effects.com/"
languageCode = "en-us"
title = "A Course on Treatment Effects"
theme = "accessible-minimalism"
disableHugoGeneratorInject = true
enableRobotsTXT = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Syllabus"
    url = "/syllabus"
    weight = 2
  [[menu.main]]
    name = "Lecture Notes"
    url = "/lecture-notes"
    weight = 2
  [[menu.main]]
    name = "Videos"
    url = "/videos"
    weight = 2
  [[menu.main]]
    name = "References"
    url = "/references"
    weight = 2
