baseURL = "https://treatment-effects.com/"
languageCode = "en-us"
title = "A Course on Treatment Effects"
theme = "accessible-minimalism"
disableHugoGeneratorInject = true
enableRobotsTXT = true

[menu]
  [[menu.main]]
    name = "About"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "The Basics"
    url = "/basics"
    weight = 2
  [[menu.main]]
    name = "Beyond the Basics"
    url = "/beyond"
    weight = 2
  [[menu.main]]
    name = "Lecture Notes"
    url = "/treatment-effects.pdf"
    weight = 2
  [[menu.main]]
    name = "Videos"
    url = "/videos"
    weight = 2
